from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    last = 'first'
    content = 'first'
    def handle_starttag(self, tag, attrs):
        self.last = 'start'
        self.content = tag

    def handle_endtag(self, tag):
        self.last = 'end'
        self.content = tag

    def handle_data(self, data):
        print(data)
            


parser = MyHTMLParser()
names = list
parser.feed("<ul><li><a href='/wiki/Theory_of_computation' title='Theory of computation'>Theory of computation</a> – branch that deals with whether and how efficiently problems can be solved on a model of computation, using an algorithm <ul><li><a href='/wiki/Automata_theory' title='Automata theory'>Automata theory</a> – study of mathematical objects called abstract machines or automata and the computational problems that can be solved using them.
<ul><li><a href='/wiki/Formal_languages' class='mw-redirect' title='Formal languages'>Formal languages</a> – set of strings of symbols.</li></ul></li>
<li><a href='/wiki/Computability_theory_(computer_science)' class='mw-redirect' title='Computability theory (computer science)'>Computability theory</a> – branch of mathematical logic and computer science that originated in the 1930s with the study of computable functions and Turing degrees.</li>
<li><a href='/wiki/Computational_complexity_theory' title='Computational complexity theory'>Computational complexity theory</a> – branch of the theory of computation in theoretical computer science and mathematics that focuses on classifying computational problems according to their inherent difficulty, and relating those classes to each other</li>
<li><a href='/wiki/Concurrency_(computer_science)#Theory' title='Concurrency (computer science)'>Concurrency theory</a> – In computer science, concurrency is a property of systems in which several computations are executing simultaneously, and potentially interacting with each other</li></ul></li>
<li><a href='/wiki/Algorithms' class='mw-redirect' title='Algorithms'>Algorithms</a> – step-by-step procedure for calculations
<ul><li><a href='/wiki/Randomized_algorithms' class='mw-redirect' title='Randomized algorithms'>Randomized algorithms</a> – algorithm which employs a degree of randomness as part of its logic.</li>
<li><a href='/wiki/Distributed_algorithms' class='mw-redirect' title='Distributed algorithms'>Distributed algorithms</a> – algorithm designed to run on computer hardware constructed from interconnected processors</li>
<li><a href='/wiki/Parallel_algorithms' class='mw-redirect' title='Parallel algorithms'>Parallel algorithms</a> – algorithm which can be executed a piece at a time on many different processing devices, and then put back together again at the end to get the correct result.</li></ul></li>
<li><a href='/wiki/Data_structures' class='mw-redirect' title='Data structures'>Data structures</a> – particular way of storing and organizing data in a computer so that it can be used efficiently.</li>
<li><a href='/wiki/Computer_architecture' title='Computer architecture'>Computer architecture</a> – In computer science and engineering, computer architecture is the practical art of selecting and interconnecting hardware components to create computers that meet functional, performance and cost goals and the formal modeling of those systems.
<ul><li><a href='/wiki/Very-large-scale_integration' title='Very-large-scale integration'>VLSI design</a> – process of creating integrated circuits by combining thousands of transistors into a single chip</li></ul></li>
<li><a href='/wiki/Operating_systems' class='mw-redirect' title='Operating systems'>Operating systems</a> – set of software that manages computer hardware resources and provides common services for computer programs</li>
<li><a href='/wiki/Computer_networking' class='mw-redirect' title='Computer networking'>Computer communications (networks)</a> – collection of hardware components and computers interconnected by communication channels that allow sharing of resources and information
<ul><li><a href='/wiki/Information_theory' title='Information theory'>Information theory</a> – branch of applied mathematics and electrical engineering involving the quantification of information</li>
<li><a href='/wiki/Internet' title='Internet'>Internet</a> – global system of interconnected computer networks that use the standard Internet protocol suite (often called TCP/IP, although not all applications use TCP) to serve billions of users worldwide.
<ul><li><a href='/wiki/World_wide_web' class='mw-redirect' title='World wide web'>World wide web</a> – part of the Internet; system of interlinked hypertext documents accessed via the Internet.</li></ul></li>
<li><a href='/wiki/Wireless_computing' class='mw-redirect' title='Wireless computing'>Wireless computing</a>  – any type of computer network that is not connected by cables of any kind.
<ul><li><a href='/wiki/Mobile_computing' title='Mobile computing'>Mobile computing</a> – form of human–computer interaction by which a computer is expected to be transported during normal usage.</li></ul></li></ul></li>
<li><a href='/wiki/Computer_security' title='Computer security'>Computer security</a> – branch of computer technology known as information security as applied to computers and networks.
<ul><li><a href='/wiki/High_availability' title='High availability'>reliability</a> – system design approach and associated service implementation that ensures a prearranged level of operational performance will be met during a contractual measurement period.</li>
<li><a href='/wiki/Outline_of_cryptography' title='Outline of cryptography'>Cryptography</a> – practice and study of hiding information.</li>
<li><a href='/wiki/Fault-tolerant_system' class='mw-redirect' title='Fault-tolerant system'>Fault-tolerant computing</a> – property that enables a system (often computer-based) to continue operating properly in the event of the failure of (or one or more faults within) some of its components</li></ul></li>
<li><a href='/wiki/Distributed_computing' title='Distributed computing'>Distributed computing</a> – field of computer science that studies distributed systems
<ul><li><a href='/wiki/Grid_computing' title='Grid computing'>Grid computing</a> – federation of computer resources from multiple administrative domains to reach a common goal</li></ul></li>
<li><a href='/wiki/Parallel_computing' title='Parallel computing'>Parallel computing</a> – form of computation in which many calculations are carried out simultaneously, operating on the principle that large problems can often be divided into smaller ones, which are then solved concurrently ('in parallel').
<ul><li><a href='/wiki/High-performance_computing' class='mw-redirect' title='High-performance computing'>High-performance computing</a> – computer at the frontline of current processing capacity, particularly speed of calculation</li></ul></li>
<li><a href='/wiki/Quantum_computing' title='Quantum computing'>Quantum computing</a> – device for computation that makes direct use of quantum mechanical phenomena, such as superposition and entanglement, to perform operations on data</li>
<li><a href='/wiki/Computer_graphics' title='Computer graphics'>Computer graphics</a> – graphics created using computers and, more generally, the representation and manipulation of image data by a computer with help from specialized software and hardware.
<ul><li><a href='/wiki/Image_processing' class='mw-redirect' title='Image processing'>Image processing</a> – any form of signal processing for which the input is an image, such as a photograph or video frame; the output of image processing may be either an image or a set of characteristics or parameters related to the image</li>
<li><a href='/wiki/Scientific_visualization' title='Scientific visualization'>Scientific visualization</a> – interdisciplinary branch of science according to Friendly (2008) 'primarily concerned with the visualization of three-dimensional phenomena (architectural, meteorological, medical, biological, etc.), where the emphasis is on realistic renderings of volumes, surfaces, illumination sources, and so forth, perhaps with a dynamic (time) component'.</li>
<li><a href='/wiki/Computational_geometry' title='Computational geometry'>Computational geometry</a> – branch of computer science devoted to the study of algorithms which can be stated in terms of geometry</li></ul></li>
<li><a href='/wiki/Outline_of_software_engineering' title='Outline of software engineering'>Software engineering</a> – application of a systematic, disciplined, quantifiable approach to the development, operation, and maintenance of software; that is the application of engineering to software
<ul><li><a href='/wiki/Formal_methods' title='Formal methods'>Formal methods</a> – particular kind of mathematically based techniques for the specification, development and verification of software and hardware systems
<ul><li><a href='/wiki/Formal_verification#Formal_verification_for_software' title='Formal verification'>Formal verification</a> – act of proving or disproving the correctness of intended algorithms underlying a system with respect to a certain formal specification or property, using formal methods of mathematics</li></ul></li></ul></li>
<li><a href='/wiki/Programming_languages' class='mw-redirect' title='Programming languages'>Programming languages</a> – artificial language designed to communicate instructions to a machine, particularly a computer
<ul><li><a href='/wiki/Programming_paradigms' class='mw-redirect' title='Programming paradigms'>Programming paradigms</a> – fundamental style of computer programming
<ul><li><a href='/wiki/Object-oriented_programming' title='Object-oriented programming'>Object-oriented programming</a> – programming paradigm using 'objects' – data structures consisting of data fields and methods together with their interactions – to design applications and computer programs</li>
<li><a href='/wiki/Functional_programming' title='Functional programming'>Functional programming</a> – programming paradigm that treats computation as the evaluation of mathematical functions and avoids state and mutable data</li></ul></li>
<li><a href='/wiki/Program_semantics' class='mw-redirect' title='Program semantics'>Program semantics</a> – field concerned with the rigorous mathematical study of the meaning of programming languages</li>
<li><a href='/wiki/Type_theory' title='Type theory'>Type theory</a> – any of several formal systems that can serve as alternatives to naive set theory, or the study of such formalisms in general</li>
<li><a href='/wiki/Compilers' class='mw-redirect' title='Compilers'>Compilers</a> – computer program (or set of programs) that transforms source code written in a programming language (the source language) into another computer language (the target language, often having a binary form known as object code)</li>
<li><a href='/wiki/Concurrent_computing#Concurrent_programming_languages' title='Concurrent computing'>Concurrent programming languages</a> – form of computing in which programs are designed as collections of interacting computational processes that may be executed in parallel</li></ul></li>
<li><a href='/wiki/Information_science' title='Information science'>Information science</a> – interdisciplinary field primarily concerned with the analysis, collection, classification, manipulation, storage, retrieval and dissemination of information
<ul><li><a href='/wiki/Database' title='Database'>Database</a> – organized collection of data, today typically in digital form
<ul><li><a href='/wiki/Relational_database' title='Relational database'>Relational database</a> – collection of data items organized as a set of formally described tables from which data can be accessed easily</li>
<li><a href='/wiki/Distributed_database' title='Distributed database'>Distributed database</a> – database in which storage devices are not all attached to a common CPU.</li>
<li><a href='/wiki/Object_database' title='Object database'>Object database</a> – database management system in which information is represented in the form of objects as used in object-oriented programming</li></ul></li>
<li><a href='/wiki/Multimedia' title='Multimedia'>Multimedia</a> – media and content that uses a combination of different content forms.</li>
<li><a href='/wiki/Hypermedia' title='Hypermedia'>hypermedia</a> – computer-based information retrieval system that enables a user to gain or provide access to texts, audio and video recordings, photographs and computer graphics related to a particular subject.</li>
<li><a href='/wiki/Data_mining' title='Data mining'>Data mining</a> – process that results in the discovery of new patterns in large data sets</li>
<li><a href='/wiki/Information_retrieval' title='Information retrieval'>Information retrieval</a> – area of study concerned with searching for documents, for information within documents, and for metadata about documents, as well as that of searching structured storage, relational databases, and the World Wide Web.</li></ul></li>
<li><a href='/wiki/Outline_of_artificial_intelligence' title='Outline of artificial intelligence'>Artificial intelligence</a> – branch of computer science that deals with intelligent behavior, learning, and adaptation in machines.
<ul><li><a href='/wiki/Automated_reasoning' title='Automated reasoning'>Automated reasoning</a> – area of computer science and mathematical logic dedicated to understand different aspects of reasoning.</li>
<li><a href='/wiki/Computer_vision' title='Computer vision'>Computer vision</a> – field that includes methods for acquiring, processing, analysing, and understanding images and, in general, high-dimensional data from the real world in order to produce numerical or symbolic information, e.g., in the forms of decisions.</li>
<li><a href='/wiki/Machine_learning' title='Machine learning'>Machine learning</a> – scientific discipline concerned with the design and development of algorithms that allow computers to evolve behaviors based on empirical data, such as from sensor data or databases
<ul><li><a href='/wiki/Artificial_neural_network' title='Artificial neural network'>Artificial neural network</a> – mathematical model or computational model that is inspired by the structure and/or functional aspects of biological neural networks</li></ul></li>
<li><a href='/wiki/Natural_language_processing' title='Natural language processing'>Natural language processing</a> – field of computer science, artificial intelligence (also called machine learning), and linguistics concerned with the interactions between computers and human (natural) languages.
<ul><li><a href='/wiki/Computational_linguistics' title='Computational linguistics'>Computational linguistics</a> – interdisciplinary field dealing with the statistical or rule-based modeling of natural language from a computational perspective.</li></ul></li>
<li><a href='/wiki/Expert_systems' class='mw-redirect' title='Expert systems'>Expert systems</a> – computer system that emulates the decision-making ability of a human expert</li>
<li><a href='/wiki/Outline_of_robotics' title='Outline of robotics'>Robotics</a> – branch of technology that deals with the design, construction, operation, structural disposition, manufacture and application of robots</li></ul></li>
<li><a href='/wiki/Human-computer_interaction' class='mw-redirect' title='Human-computer interaction'>Human-computer interaction</a> – study, planning, and design of the interaction between people (users) and computers.
<ul><li><a href='/wiki/Numerical_analysis' title='Numerical analysis'>Numerical analysis</a> – study of algorithms that use numerical approximation (as opposed to general symbolic manipulations) for the problems of mathematical analysis (as distinguished from discrete mathematics).</li>
<li><a href='/wiki/Symbolic_computation' class='mw-redirect' title='Symbolic computation'>Algebraic (symbolic) computation</a> – relates to algorithms and software for manipulating mathematical expressions and equations in symbolic form, as opposed to manipulating the approximations of specific numerical quantities represented by those symbols. Software applications that perform symbolic calculations are called computer algebra systems.</li>
<li><a href='/wiki/Computational_number_theory' title='Computational number theory'>Computational number theory</a> – study of algorithms for performing number theoretic computations</li>
<li><a href='/wiki/Computational_mathematics' title='Computational mathematics'>Computational mathematics</a> – involves mathematical research in areas of science where computing plays a central and essential role, emphasizing algorithms, numerical methods, and symbolic methods</li>
<li><a href='/wiki/Scientific_computing' class='mw-redirect' title='Scientific computing'>Scientific computing (Computational science)</a> –</li>
<li><a href='/wiki/Computational_biology' title='Computational biology'>Computational biology (bioinformatics)</a> – involves the development and application of data-analytical and theoretical methods, mathematical modeling and computational simulation techniques to the study of biological, behavioral, and social systems.</li>
<li><a href='/wiki/Computational_science' title='Computational science'>Computational science</a> – subfield of computer science concerned with constructing mathematical models and quantitative analysis techniques and using computers to analyze and solve scientific problems</li>
<li><a href='/wiki/Computational_chemistry' title='Computational chemistry'>Computational chemistry</a> – branch of chemistry that uses principles of computer science to assist in solving chemical problems</li>
<li><a href='/wiki/Computational_neuroscience' title='Computational neuroscience'>Computational neuroscience</a> – study of brain function in terms of the information processing properties of the structures that make up the nervous system.</li>
<li><a href='/wiki/Computer-aided_engineering' title='Computer-aided engineering'>Computer-aided engineering</a> – broad usage of computer software to aid in engineering tasks.
<ul><li><a href='/wiki/Finite_element_analysis' class='mw-redirect' title='Finite element analysis'>Finite element analysis</a> – numerical technique for finding approximate solutions of partial differential equations (PDE) as well as integral equations.</li>
<li><a href='/wiki/Computational_fluid_dynamics' title='Computational fluid dynamics'>Computational fluid dynamics</a> – branch of fluid mechanics that uses numerical methods and algorithms to solve and analyze problems that involve fluid flows.</li></ul></li>
<li><a href='/wiki/Computational_economics' title='Computational economics'>Computational economics</a> – research discipline at the interface between computer science and economic and management science</li>
<li><a href='/wiki/Computational_sociology' title='Computational sociology'>Computational sociology</a> – branch of sociology that uses computationally intensive methods to analyze and model social phenomena.</li>
<li><a href='/wiki/Computational_finance' title='Computational finance'>Computational finance</a> – cross-disciplinary field which relies on computational intelligence, mathematical finance, numerical methods and computer simulations to make trading, hedging and investment decisions, as well as facilitating the risk management of those decisions</li>
<li><a href='/wiki/Digital_Humanities' class='mw-redirect' title='Digital Humanities'>Humanities computing (Digital Humanities)</a> – area of research, teaching, and creation concerned with the intersection of computing and the disciplines of the humanities</li></ul></li>
<li><a href='/wiki/Information_systems' class='mw-redirect' title='Information systems'>Information systems</a> – study of complementary networks of hardware and software that people and organizations use to collect, filter, process, create, and distribute data
<ul><li><a href='/wiki/Business_informatics' title='Business informatics'>Business informatics</a> – discipline combining information technology (IT), informatics and management concepts.</li>
<li><a href='/wiki/Outline_of_information_technology' title='Outline of information technology'>Information technology</a> –</li>
<li><a href='/wiki/Management_information_systems' class='mw-redirect' title='Management information systems'>Management information systems</a> – provides information that is needed to manage organizations efficiently and effectively</li>
<li><a href='/wiki/Health_informatics' title='Health informatics'>Health informatics</a> – discipline at the intersection of information science, computer science, and health care.</li></ul></li></ul></li>
<li><a href='/wiki/Outline_of_mathematics' title='Outline of mathematics'>Mathematics</a> – search for fundamental truths in pattern, quantity, and change. <i>(See also <a href='/wiki/List_of_mathematics_lists#Fields_of_mathematics' class='mw-redirect' title='List of mathematics lists'>Branches of Mathematics</a> and AMS <a rel='nofollow' class='external text' href='http://www.ams.org/msc/'>Mathematics Subject Classification</a>)</i>
<ul><li><a href='/wiki/Outline_of_algebra' title='Outline of algebra'>Algebra</a> – one of the main branches of mathematics, it concerns the study of structure, relation and quantity.
<ul><li><a href='/wiki/Group_theory' title='Group theory'>Group theory</a> – studies the algebraic structures known as groups.
<ul><li><a href='/wiki/Group_representation' title='Group representation'>Group representation</a> – describe abstract groups in terms of linear transformations of vector spaces</li></ul></li>
<li><a href='/wiki/Ring_theory' title='Ring theory'>Ring theory</a> – study of ring–algebraic structures in which addition and multiplication are defined and have similar properties to those familiar from the integers</li>
<li><a href='/wiki/Field_theory_(mathematics)' class='mw-redirect' title='Field theory (mathematics)'>Field theory</a> – branch of mathematics which studies the properties of fields</li>
<li><a href='/wiki/Linear_algebra' title='Linear algebra'>Linear algebra</a> – branch of mathematics concerning finite or countably infinite dimensional vector spaces, as well as linear mappings between such spaces.
<ul><li><a href='/wiki/Vector_space' title='Vector space'>Vector space</a> – mathematical structure formed by a collection of vectors: objects that may be added together and multiplied ('scaled') by numbers, called scalars in this context.</li></ul></li>
<li><a href='/wiki/Multilinear_algebra' title='Multilinear algebra'>Multilinear algebra</a> – extends the methods of linear algebra</li>
<li><a href='/wiki/Lie_algebra' title='Lie algebra'>Lie algebra</a> – algebraic structure whose main use is in studying geometric objects such as Lie groups and differentiable manifolds</li>
<li><a href='/wiki/Associative_algebra' title='Associative algebra'>Associative algebra</a> – associative ring that has a compatible structure of a vector space over a certain field K or, more generally, of a module over a commutative ring R.</li>
<li><a href='/wiki/Non-associative_algebra' title='Non-associative algebra'>Non-associative algebra</a> – K-vector space (or more generally a module) A equipped with a K-bilinear map</li>
<li><a href='/wiki/Universal_algebra' title='Universal algebra'>Universal algebra</a> – field of mathematics that studies algebraic structures themselves, not examples ('models') of algebraic structures</li>
<li><a href='/wiki/Homological_algebra' title='Homological algebra'>Homological algebra</a> – branch of mathematics which studies homology in a general algebraic setting</li>
<li><a href='/wiki/Category_theory' title='Category theory'>Category theory</a> – area of study in mathematics that examines in an abstract way the properties of particular mathematical concepts, by formalising them as collections of objects and arrows (also called morphisms, although this term also has a specific, non-category-theoretical sense), where these collections satisfy some basic conditions</li>
<li><a href='/wiki/Lattice_theory' class='mw-redirect' title='Lattice theory'>Lattice theory</a> – partially ordered set in which any two elements have a unique supremum (also called a least upper bound or join) and a unique infimum (also called a greatest lower bound or meet).
<ul><li><a href='/wiki/Order_theory' title='Order theory'>Order theory</a> – branch of mathematics which investigates our intuitive notion of order using binary relations.</li></ul></li>
<li><a href='/wiki/Differential_algebra' title='Differential algebra'>Differential algebra</a> – algebras equipped with a derivation, which is a unary function that is linear and satisfies the Leibniz product rule.</li></ul></li>
<li><a href='/wiki/Mathematical_analysis' title='Mathematical analysis'>Analysis</a> – branch of pure mathematics that includes the theories of differentiation, integration and measure, limits, infinite series, and analytic functions
<ul><li><a href='/wiki/Real_analysis' title='Real analysis'>Real analysis</a> – branch of mathematical analysis dealing with the set of real numbers and functions of a real variable.
<ul><li><a href='/wiki/Outline_of_calculus' title='Outline of calculus'>Calculus</a> – branch of mathematics focused on limits, functions, derivatives, integrals, and infinite series.</li></ul></li>
<li><a href='/wiki/Complex_analysis' title='Complex analysis'>Complex analysis</a> – branch of mathematical analysis that investigates functions of complex numbers</li>
<li><a href='/wiki/Functional_analysis' title='Functional analysis'>Functional analysis</a> – branch of mathematical analysis, the core of which is formed by the study of vector spaces endowed with some kind of limit-related structure (e.g. inner product, norm, topology, etc.) and the linear operators acting upon these spaces and respecting these structures in a suitable sense
<ul><li><a href='/wiki/Operator_theory' title='Operator theory'>Operator theory</a> – branch of functional analysis that focuses on bounded linear operators, but which includes closed operators and nonlinear operators.</li></ul></li>
<li><a href='/wiki/Non-standard_analysis' title='Non-standard analysis'>Non-standard analysis</a> – branch of classical mathematics that formulates analysis using a rigorous notion of an infinitesimal number.</li>
<li><a href='/wiki/Harmonic_analysis' title='Harmonic analysis'>Harmonic analysis</a> – branch of mathematics concerned with the representation of functions or signals as the superposition of basic waves, and the study of and generalization of the notions of Fourier series and Fourier transforms.</li>
<li><a href='/wiki/P-adic_analysis' title='P-adic analysis'>p-adic analysis</a> – branch of number theory that deals with the mathematical analysis of functions of p-adic numbers.</li>
<li><a href='/wiki/Ordinary_differential_equations' class='mw-redirect' title='Ordinary differential equations'>Ordinary differential equations</a> – ordinary differential equation (ODE) is an equation in which there is only one independent variable and one or more derivatives of a dependent variable with respect to the independent variable, so that all the derivatives occurring in the equation are ordinary derivatives.</li>
<li><a href='/wiki/Partial_differential_equations' class='mw-redirect' title='Partial differential equations'>Partial differential equations</a> – differential equation that contains unknown multivariable functions and their partial derivatives.</li></ul></li>
<li><a href='/wiki/Probability_theory' title='Probability theory'>Probability theory</a> – branch of mathematics concerned with probability, the analysis of random phenomena.
<ul><li><a href='/wiki/Measure_theory' class='mw-redirect' title='Measure theory'>Measure theory</a> – systematic way to assign a number to each suitable subset of that set, intuitively interpreted as its size.</li>
<li><a href='/wiki/Ergodic_theory' title='Ergodic theory'>Ergodic theory</a> – branch of mathematics that studies dynamical systems with an invariant measure and related problems.</li>
<li><a href='/wiki/Stochastic_process' title='Stochastic process'>Stochastic process</a> – collection of random variables; this is often used to represent the evolution of some random value, or system, over time.</li></ul></li>
<li><a href='/wiki/Outline_of_geometry' title='Outline of geometry'>Geometry</a> – branch of mathematics concerned with questions of shape, size, relative position of figures, and the properties of space. Geometry is one of the oldest mathematical sciences.
<ul><li><a href='/wiki/Topology' title='Topology'>Topology</a> – major area of mathematics concerned with properties that are preserved under continuous deformations of objects, such as deformations that involve stretching, but no tearing or gluing.</li>
<li><a href='/wiki/General_topology' title='General topology'>General topology</a> – branch of topology which studies properties of topological spaces and structures defined on them.</li>
<li><a href='/wiki/Algebraic_topology' title='Algebraic topology'>Algebraic topology</a> – branch of mathematics which uses tools from abstract algebra to study topological spaces</li>
<li><a href='/wiki/Geometric_topology' title='Geometric topology'>Geometric topology</a> – study of manifolds and maps between them, particularly embeddings of one manifold into another.</li>
<li><a href='/wiki/Differential_topology' title='Differential topology'>Differential topology</a> – field dealing with differentiable functions on differentiable manifolds</li>
<li><a href='/wiki/Algebraic_geometry' title='Algebraic geometry'>Algebraic geometry</a> – branch of mathematics which combines techniques of abstract algebra, especially commutative algebra, with the language and the problems of geometry</li>
<li><a href='/wiki/Differential_geometry' title='Differential geometry'>Differential geometry</a> – mathematical discipline that uses the techniques of differential calculus and integral calculus, as well as linear algebra and multilinear algebra, to study problems in geometry</li>
<li><a href='/wiki/Projective_geometry' title='Projective geometry'>Projective geometry</a> – study of geometric properties that are invariant under projective transformations</li>
<li><a href='/wiki/Affine_geometry' title='Affine geometry'>Affine geometry</a> – study of geometric properties which remain unchanged by affine transformations</li>
<li><a href='/wiki/Non-Euclidean_geometry' title='Non-Euclidean geometry'>Non-Euclidean geometry</a> – either of two specific geometries that are, loosely speaking, obtained by negating the Euclidean parallel postulate, namely hyperbolic and elliptic geometry.</li>
<li><a href='/wiki/Convex_geometry' title='Convex geometry'>Convex geometry</a> – branch of geometry studying convex sets, mainly in Euclidean space.</li>
<li><a href='/wiki/Discrete_geometry' title='Discrete geometry'>Discrete geometry</a> – branch of geometry that studies combinatorial properties and constructive methods of discrete geometric objects.</li></ul></li>
<li><a href='/wiki/Outline_of_trigonometry' title='Outline of trigonometry'>Trigonometry</a> – branch of mathematics that studies relationships involving lengths and angles of triangles</li>
<li><a href='/wiki/Number_theory' title='Number theory'>Number theory</a> – branch of pure mathematics devoted primarily to the study of the integers
<ul><li><a href='/wiki/Analytic_number_theory' title='Analytic number theory'>Analytic number theory</a> – branch of number theory that uses methods from mathematical analysis to solve problems about the integers</li>
<li><a href='/wiki/Algebraic_number_theory' title='Algebraic number theory'>Algebraic number theory</a> – major branch of number theory which studies algebraic structures related to algebraic integers</li>
<li><a href='/wiki/Geometric_number_theory' class='mw-redirect' title='Geometric number theory'>Geometric number theory</a> – studies convex bodies and integer vectors in n-dimensional space</li></ul></li>
<li><a href='/wiki/Mathematical_logic' title='Mathematical logic'>Logic</a> and <a href='/wiki/Foundations_of_mathematics' title='Foundations of mathematics'>Foundations of mathematics</a> – subfield of mathematics with close connections to the foundations of mathematics, theoretical computer science and philosophical logic.
<ul><li><a href='/wiki/Set_theory' title='Set theory'>Set theory</a> – branch of mathematics that studies sets, which are collections of objects</li>
<li><a href='/wiki/Proof_theory' title='Proof theory'>Proof theory</a> – branch of mathematical logic that represents proofs as formal mathematical objects, facilitating their analysis by mathematical techniques</li>
<li><a href='/wiki/Model_theory' title='Model theory'>Model theory</a> – study of (classes of) mathematical structures (e.g. groups, fields, graphs, universes of set theory) using tools from mathematical logic</li>
<li><a href='/wiki/Recursion_theory' class='mw-redirect' title='Recursion theory'>Recursion theory</a> – branch of mathematical logic and computer science that originated in the 1930s with the study of computable functions and Turing degrees</li>
<li><a href='/wiki/Modal_logic' title='Modal logic'>Modal logic</a> – type of formal logic primarily developed in the 1960s that extends classical propositional and predicate logic to include operators expressing modality</li>
<li><a href='/wiki/Intuitionistic_logic' title='Intuitionistic logic'>Intuitionistic logic</a> – symbolic logic system differing from classical logic in its definition of the meaning of a statement being true</li></ul></li>
<li><a href='/wiki/Applied_mathematics' title='Applied mathematics'>Applied mathematics</a> – branch of mathematics that concerns itself with mathematical methods that are typically used in science, engineering, business, and industry.
<ul><li><a href='/wiki/Mathematical_statistics' title='Mathematical statistics'>Mathematical statistics</a> – study of statistics from a mathematical standpoint, using probability theory as well as other branches of mathematics such as linear algebra and analysis
<ul><li><a href='/wiki/Outline_of_probability' title='Outline of probability'>Probability</a> – likelihood or chance that something is the case or will happen</li>
<li><a href='/wiki/Econometrics' title='Econometrics'>Econometrics</a> – application of mathematics and statistical methods to economic data</li>
<li><a href='/wiki/Outline_of_actuarial_science' title='Outline of actuarial science'>Actuarial science</a> – discipline that applies mathematical and statistical methods to assess risk in the insurance and finance industries.</li>
<li><a href='/wiki/Demography' title='Demography'>Demography</a> – statistical study of human populations and sub-populations.</li></ul></li>
<li><a href='/wiki/Approximation_theory' title='Approximation theory'>Approximation theory</a> – study of how functions can best be approximated with simpler functions, and with quantitatively characterizing the errors introduced thereby.</li>
<li><a href='/wiki/Numerical_analysis' title='Numerical analysis'>Numerical analysis</a> – study of algorithms that use numerical approximation (as opposed to general symbolic manipulations) for the problems of mathematical analysis (as distinguished from discrete mathematics).</li>
<li><a href='/wiki/Optimization_(mathematics)' class='mw-redirect' title='Optimization (mathematics)'>Optimization (Mathematical programming)</a> – selection of a best element from some set of available alternatives.
<ul><li><a href='/wiki/Operations_research' title='Operations research'>Operations research</a> – study of the application of advanced analytical methods to help make better decisions</li>
<li><a href='/wiki/Linear_programming' title='Linear programming'>Linear programming</a> – mathematical method for determining a way to achieve the best outcome (such as maximum profit or lowest cost) in a given mathematical model for some list of requirements represented as linear relationships</li></ul></li>
<li><a href='/wiki/Dynamical_systems' class='mw-redirect' title='Dynamical systems'>Dynamical systems</a> – concept in mathematics where a fixed rule describes the time dependence of a point in a geometrical space
<ul><li><a href='/wiki/Chaos_theory' title='Chaos theory'>Chaos theory</a> – study of the behavior of dynamical systems that are highly sensitive to initial conditions, an effect which is popularly referred to as the butterfly effect.</li>
<li><a href='/wiki/Fractal_geometry' class='mw-redirect' title='Fractal geometry'>Fractal geometry</a> – mathematical set that has a fractal dimension that usually exceeds its topological dimension and may fall between the integers.</li></ul></li>
<li><a href='/wiki/Mathematical_physics' title='Mathematical physics'>Mathematical physics</a> – development of mathematical methods for application to problems in physics
<ul><li><a href='/wiki/Quantum_field_theory' title='Quantum field theory'>Quantum field theory</a> – theoretical framework for constructing quantum mechanical models of systems classically parametrized (represented) by an infinite number of degrees of freedom, that is, fields and (in a condensed matter context) many-body systems.</li>
<li><a href='/wiki/Statistical_mechanics' title='Statistical mechanics'>Statistical mechanics</a> – branch of physics that applies probability theory, which contains mathematical tools for dealing with large populations, to the study of the thermodynamic behavior of systems composed of a large number of particles.</li></ul></li>
<li><a href='/wiki/Information_theory' title='Information theory'>Information theory</a> – branch of applied mathematics and electrical engineering involving the quantification of information.</li>
<li><a href='/wiki/Outline_of_cryptography' title='Outline of cryptography'>Cryptography</a> – study of means of obscuring information, such as codes and ciphers</li>
<li><a href='/wiki/Combinatorics' title='Combinatorics'>Combinatorics</a> – branch of mathematics concerning the study of finite or countable discrete structures
<ul><li><a href='/wiki/Coding_theory' title='Coding theory'>Coding theory</a> – study of the properties of codes and their fitness for a specific application</li></ul></li>
<li><a href='/wiki/Graph_theory' title='Graph theory'>Graph theory</a> – study of graphs, mathematical structures used to model pairwise relations between objects from a certain collection</li>
<li><a href='/wiki/Game_theory' title='Game theory'>Game theory</a> – study of strategic decision making. More formally, it is 'the study of mathematical models of conflict and cooperation between intelligent rational decision-makers.'</li></ul></li></ul></li>
<li><a href='/wiki/Outline_of_statistics' title='Outline of statistics'>Statistics</a> – collection, analysis, interpretation, and presentation of data.
<ul><li><a href='/wiki/Computational_statistics' title='Computational statistics'>Computational statistics</a> – interface between statistics and computer science.
<ul><li><a href='/wiki/Data_mining' title='Data mining'>Data mining</a> – process that results in the discovery of new patterns in large data sets</li>
<li><a href='/wiki/Regression_analysis' title='Regression analysis'>Regression</a> – estimates the conditional expectation of the dependent variable given the independent variables – that is, the average value of the dependent variable when the independent variables are held fixed.</li>
<li><a href='/wiki/Simulation' title='Simulation'>Simulation</a> – Simulation is the imitation of the operation of a real-world process or system over time. The act of simulating something first requires that a model be developed; this model represents the key characteristics or behaviors of the selected physical or abstract system or process. The model represents the system itself, whereas the simulation represents the operation of the system over time.
<ul><li><a href='/wiki/Bootstrap_(statistics)' class='mw-redirect' title='Bootstrap (statistics)'>Bootstrap (statistics)</a> – method for assigning measures of accuracy to sample estimates (Efron and Tibshirani 1993).</li></ul></li></ul></li>
<li><a href='/wiki/Design_of_experiments' title='Design of experiments'>Design of experiments</a> – design of any information-gathering exercises where variation is present, whether under the full control of the experimenter or not
<ul><li><a href='/wiki/Block_design' title='Block design'>Block design</a> – set together with a family of subsets (repeated subsets are allowed at times) whose members are chosen to satisfy some set of properties that are deemed useful for a particular application.</li>
<li><a href='/wiki/Analysis_of_variance' title='Analysis of variance'>Analysis of variance</a> – collection of statistical models, and their associated procedures, in which the observed variance in a particular variable is partitioned into components attributable to different sources of variation.</li>
<li><a href='/wiki/Response_surface_methodology' title='Response surface methodology'>Response surface methodology</a> – explores the relationships between several explanatory variables and one or more response variables.</li></ul></li>
<li><a href='/wiki/Engineering_statistics' title='Engineering statistics'>Engineering statistics</a> – Engineering statistics combines engineering and statistics</li>
<li><a href='/wiki/Spatial_statistics' class='mw-redirect' title='Spatial statistics'>Spatial statistics</a> – any of the formal techniques which study entities using their topological, geometric, or geographic properties.</li>
<li><a href='/wiki/Social_statistics' title='Social statistics'>Social statistics</a> – use of statistical measurement systems to study human behavior in a social environment</li>
<li><a href='/wiki/Statistical_model' title='Statistical model'>Statistical modelling</a> – formalization of relationships between variables in the form of mathematical equations
<ul><li><a href='/wiki/Biostatistics' title='Biostatistics'>Biostatistics</a> – application of statistics to a wide range of topics in biology.
<ul><li><a href='/wiki/Epidemiology' title='Epidemiology'>Epidemiology</a> – study of the distribution and patterns of health-events, health-characteristics and their causes or influences in well-defined populations.</li></ul></li>
<li><a href='/wiki/Multivariate_analysis' title='Multivariate analysis'>Multivariate analysis</a> – observation and analysis of more than one statistical variable at a time.
<ul><li><a href='/wiki/Structural_equation_model' class='mw-redirect' title='Structural equation model'>Structural equation model</a> – statistical technique for testing and estimating causal relations using a combination of statistical data and qualitative causal assumptions.</li>
<li><a href='/wiki/Time_series' title='Time series'>Time series</a> – sequence of data points, measured typically at successive time instants spaced at uniform time intervals.</li></ul></li>
<li><a href='/wiki/Reliability_theory' class='mw-redirect' title='Reliability theory'>Reliability theory</a> – describes the probability of a system completing its expected function during an interval of time.</li>
<li><a href='/wiki/Quality_control' title='Quality control'>Quality control</a> – process by which entities review the quality of all factors involved in production.</li></ul></li>
<li><a href='/wiki/Statistical_theory' title='Statistical theory'>Statistical theory</a> – provides a basis for the whole range of techniques, in both study design and data analysis, that are used within applications of statistics.
<ul><li><a href='/wiki/Decision_theory' title='Decision theory'>Decision theory</a> – identifies the values, uncertainties and other issues relevant in a given decision, its rationality, and the resulting optimal decision.</li>
<li><a href='/wiki/Mathematical_statistics' title='Mathematical statistics'>Mathematical statistics</a> – study of statistics from a mathematical standpoint, using probability theory as well as other branches of mathematics such as linear algebra and analysis.
<ul><li><a href='/wiki/Outline_of_probability' title='Outline of probability'>Probability</a> – likelihood or chance that something is the case or will happen.</li></ul></li></ul></li>
<li><a href='/wiki/Survey_Sampling' class='mw-redirect' title='Survey Sampling'>Sample Survey</a> – process of selecting a sample of elements from a target population in order to conduct a survey.
<ul><li><a href='/wiki/Statistics' title='Statistics'>Sampling theory</a> – study of the collection, organization, analysis, and interpretation of data.</li>
<li><a href='/wiki/Survey_(statistics)' class='mw-redirect' title='Survey (statistics)'>Survey methodology</a> – field that studies the sampling of individuals from a population with a view towards making statistical inferences about the population using the sample.</li></ul></li></ul></li>
<li><a href='/wiki/Systems_science' title='Systems science'>Systems science</a> – interdisciplinary field of science that studies the nature of complex systems in nature, society, and science.
<ul><li><a href='/wiki/Chaos_theory' title='Chaos theory'>Chaos theory</a> – field of study in mathematics, with applications in several disciplines including physics, engineering, economics, biology, and philosophy; studies the behavior of dynamical systems that are highly sensitive to initial conditions.</li>
<li><a href='/wiki/Complex_systems' class='mw-redirect' title='Complex systems'>Complex systems</a> and Complexity Theory – studies how relationships between parts give rise to the collective behaviors of a system and how the system interacts and forms relationships with its environment.</li>
<li><a href='/wiki/Cybernetics' title='Cybernetics'>Cybernetics</a> – interdisciplinary study of the structure of regulatory systems.
<ul><li><a href='/wiki/Biocybernetics' title='Biocybernetics'>Biocybernetics</a> – application of cybernetics to biological science, composed of biological disciplines that benefit from the application of cybernetics: neurology, multicellular systems and others.</li>
<li><a href='/wiki/Engineering_cybernetics' title='Engineering cybernetics'>Engineering cybernetics</a> – field of cybernetics, which deals with the question of control engineering of mechatronic systems as well as chemical or biological systems.</li>
<li><a href='/wiki/Management_cybernetics' title='Management cybernetics'>Management cybernetics</a> – field of cybernetics concerned with management and organizations.</li>
<li><a href='/wiki/Medical_cybernetics' title='Medical cybernetics'>Medical cybernetics</a> – branch of cybernetics which has been heavily affected by the development of the computer, which applies the concepts of cybernetics to medical research and practice.</li>
<li><a href='/wiki/New_Cybernetics' class='mw-redirect' title='New Cybernetics'>New Cybernetics</a> – study of self-organizing systems according to Peter Harries-Jones (1988), 'looking beyond the issues of the 'first', 'old' or 'original' cybernetics and their politics and sciences of control, to the autonomy and self-organization capabilities of complex systems'.</li>
<li><a href='/wiki/Second-order_cybernetics' title='Second-order cybernetics'>Second-order cybernetics</a> – investigates the construction of models of cybernetic systems.</li></ul></li>
<li><a href='/wiki/Control_theory' title='Control theory'>Control theory</a> – Control theory is an interdisciplinary branch of engineering and mathematics that deals with the behavior of dynamical systems. The external input of a system is called the reference. When one or more output variables of a system need to follow a certain reference over time, a controller manipulates the inputs to a system to obtain the desired effect on the output of the system.
<ul><li><a href='/wiki/Control_engineering' title='Control engineering'>Control engineering</a> – engineering discipline that applies control theory to design systems with desired behaviors.</li>
<li><a href='/wiki/Control_systems' class='mw-redirect' title='Control systems'>Control systems</a> – device, or set of devices to manage, command, direct or regulate the behavior of other devices or system.</li>
<li><a href='/wiki/Dynamical_systems' class='mw-redirect' title='Dynamical systems'>Dynamical systems</a> – concept in mathematics where a fixed rule describes the time dependence of a point in a geometrical space.</li></ul></li>
<li><a href='/wiki/Operations_research' title='Operations research'>Operations research</a> – study of the use of advanced analytical methods to help make better decisions.</li>
<li><a href='/wiki/Systems_dynamics' class='mw-redirect' title='Systems dynamics'>Systems dynamics</a> – approach to understanding the behaviour of complex systems over time.
<ul><li><a href='/wiki/Systems_analysis' title='Systems analysis'>Systems analysis</a> – study of sets of interacting entities, including computer systems analysis.</li></ul></li>
<li><a href='/wiki/Systems_theory' title='Systems theory'>Systems theory</a> – interdisciplinary study of systems in general, with the goal of elucidating principles that can be applied to all types of systems at all nesting levels in all fields of research.
<ul><li><a href='/wiki/Developmental_systems_theory' title='Developmental systems theory'>Developmental systems theory</a> – overarching theoretical perspective on biological development, heredity, and evolution</li>
<li><a href='/wiki/General_systems_theory' class='mw-redirect' title='General systems theory'>General systems theory</a> – interdisciplinary study of systems in general, with the goal of elucidating principles that can be applied to all types of systems at all nesting levels in all fields of research.</li>
<li><a href='/wiki/LTI_system_theory' class='mw-redirect' title='LTI system theory'>Linear time-invariant systems</a> – investigates the response of a linear and time-invariant system to an arbitrary input signal.</li>
<li><a href='/wiki/Mathematical_system_theory' class='mw-redirect' title='Mathematical system theory'>Mathematical system theory</a> – area of mathematics used to describe the behavior of complex dynamical systems, usually by employing differential equations or difference equations.</li>
<li><a href='/wiki/Systems_biology' title='Systems biology'>Systems biology</a> – several related trends in bioscience research, and a movement that draws on those trends.</li>
<li><a href='/wiki/Systems_ecology' title='Systems ecology'>Systems ecology</a> – interdisciplinary field of ecology, taking a holistic approach to the study of ecological systems, especially ecosystems.</li>
<li><a href='/wiki/Systems_engineering' title='Systems engineering'>Systems engineering</a> – interdisciplinary field of engineering focusing on how complex engineering projects should be designed and managed over their life cycles.</li>
<li><a href='/wiki/Systems_neuroscience' title='Systems neuroscience'>Systems neuroscience</a> – subdiscipline of neuroscience and systems biology that studies the function of neural circuits and systems.</li>
<li><a href='/wiki/Systems_psychology' title='Systems psychology'>Systems psychology</a> – branch of applied psychology that studies human behaviour and experience in complex systems.</li></ul></li></ul></li></ul>")
